language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  global:
  - DATABASE_URI='postgres://postgres:@localhost:5432/testdb'

before_script:
  - psql -c 'create database testdb;' -U postgres
  - chromedriver --version
  - curl -X GET http://localhost:5984/
  - curl -X PUT http://admin:pass@localhost:5984/test
  - gunicorn --log-level=critical --bind=127.0.0.1:8080 service:app &  # start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc
  - curl -I http://localhost:8080/  # make sure the service is up

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver 
      - python3-selenium

# command to run tests
jobs:
  include:
    - stage: Test
      name: TDD
      script: nosetests

    - stage: Test
      name: BDD
      script: behave

after_success:
 - codecov
